languageCode = "en-us"
title = "Caviar For Fish"
theme = "beautifulhugo"
baseURL = "http://lucindax.github.io/"
newContentEditor = "vim"
pygmentsStyle = "native"
pygmentsUseClasses = true
PygmentsCodeFences = true
canonifyURLs = true
disqusShortname = "caviarforfish"
publishDir = "docs"

[Params]
  subtitle = "return false"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  commit = false
  dateFormat = "January 2, 2006"
  rss = true

[Author]
  name = "Ahmed Osman"
  email = "ahmedosmanazrk@gmail.com"
  github = "lucindax"
  twitter = "la_legume"

[[menu.main]]
  name = "Blog"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/page/about"
  weight = 3

[[menu.main]]
  name = "Resume"
  url = "/page/resume"
  weight = 4

